version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs: 
  aws-ecr:
    docker:
      - image: circleci/python:3.7
  # environment:
  #    - AWS_DEV_ACCESS_KEY_ID: ${AWS_DEV_ACCESS_KEY_ID}
  #    - AWS_DEV_SECRET_ACCESS_KEY: ${AWS_DEV_SECRET_ACCESS_KEY}
  #    - AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  
    steps:
       - checkout     
       - run:
           name: Build and tag Docker image
           command: |
               docker build -t black -f ./Dockerfile .
               docker tag black:latest 148774211651.dkr.ecr.us-east-1.amazonaws.com/black:latest
       - run:
             name: Login to ECR
             command: |
               aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 148774211651.dkr.ecr.us-east-1.amazonaws.com
       - run:
             name: Push Docker image to ECR
             command: docker push 148774211651.dkr.ecr.us-east-1.amazonaws.com/black:latest  
             
       - aws-ecr/build-and-push-image:
              dockerfile: black-22.12.0/Dockerfile
              repo: black     

workflows:
  build-and-push-to-ecr:
    jobs:
      - aws-ecr:
          context:
            - AWS_ECR_DEMO
          filters:
            branches:
              only:
                - master
