version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs: 
  aws-ecr:
    docker:
      - image: circleci/python:3.7
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/build-and-push-image:
          dockerfile: ./Dockerfile
          repo: black
          tag: 22.12.0
workflows:
  build-and-push-to-ecr:
    jobs:
      - aws-ecr:
          context:
            - AWS_ECR_DEMO
          filters:
            branches:
              only:
                - master
