version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs: 
  aws-ecr:
    docker:
      - image: circleci/python:3.7  
    steps:
       - checkout 
       - setup_remote_docker:
          version: 20.10.11   
       - run:
           name: Build and tag Docker image
           command: |
               docker build -t black:22.12.0 -f Dockerfile .
               docker tag black:22.12.0 148774211651.dkr.ecr.us-east-1.amazonaws.com/black:22.12.0
       - run: docker buildx install --install-version latest                
       - aws-ecr/build-and-push-image:
              dockerfile: Dockerfile
              repo: black     
              #tag: 22.12.0

workflows:
  version: 2
  master:
    jobs:
     - aws-ecr:
        context: 
          -AWS_ECR_DEMO

